#!/usr/bin/env python
"""Download and self-host the UI typefaces (Geist + Geist Mono).

The app is an offline tool, so the chrome cannot depend on fonts.googleapis.com.
This fetches the latin / latin-ext subsets once, writes the woff2 files into
app/public/fonts/ui/, and emits app/public/fonts/ui-fonts.css with local URLs.

Run: python scripts/fetch-ui-fonts.py
"""
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, 'app', 'public', 'fonts', 'ui')
CSS_OUT = os.path.join(ROOT, 'app', 'public', 'fonts', 'ui-fonts.css')

UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')

# Only the subsets the UI actually needs — keeps the payload small.
KEEP_SUBSETS = {'latin', 'latin-ext'}

FAMILIES = [
    ('Geist', 'Geist:wght@400;500;600;700'),
    ('Geist Mono', 'Geist+Mono:wght@400;500;600'),
]


def fetch(url):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=30) as res:
        return res.read()


def slug(text):
    return re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    out_blocks = []

    for family, query in FAMILIES:
        css = fetch(f'https://fonts.googleapis.com/css2?family={query}&display=swap').decode()
        # Each face is preceded by a /* subset */ comment.
        pattern = re.compile(
            r'/\*\s*([a-z0-9-]+)\s*\*/\s*@font-face\s*\{(.*?)\}', re.S)
        for subset, body in pattern.findall(css):
            if subset not in KEEP_SUBSETS:
                continue
            weight = re.search(r'font-weight:\s*(\d+)', body).group(1)
            style = re.search(r'font-style:\s*(\w+)', body).group(1)
            url = re.search(r'url\((https://[^)]+\.woff2)\)', body).group(1)
            urange = re.search(r'unicode-range:\s*([^;]+);', body).group(1).strip()

            filename = f'{slug(family)}-{weight}-{subset}.woff2'
            target = os.path.join(OUT_DIR, filename)
            if not os.path.exists(target):
                data = fetch(url)
                with open(target, 'wb') as fh:
                    fh.write(data)
                print(f'  downloaded {filename} ({len(data) / 1024:.1f} KB)')
            else:
                print(f'  cached     {filename}')

            out_blocks.append(
                '@font-face{'
                f'font-family:"{family}";font-style:{style};font-weight:{weight};'
                'font-display:swap;'
                f'src:url(/fonts/ui/{filename}) format("woff2");'
                f'unicode-range:{urange};'
                '}')

    header = (
        '/* UI typefaces — self-hosted so the app works fully offline.\n'
        '   Generated by scripts/fetch-ui-fonts.py; do not edit by hand.\n'
        '   Balsamiq Sans stays separate (see fonts.css) and is scoped to the\n'
        '   SVG roadmap canvas, which is the fidelity contract. */\n')
    with open(CSS_OUT, 'w', encoding='utf-8') as fh:
        fh.write(header + '\n'.join(out_blocks) + '\n')
    print(f'\nwrote {CSS_OUT} ({len(out_blocks)} faces)')


if __name__ == '__main__':
    main()
